name: Verify Format C/C++ and Verilog

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verify-cpp-format:
    name: Check C/C++ Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: '.'
          extensions: 'c,h,cpp,hpp'
          clangFormatVersion: 14
          style: file:ci/.clang-format
  
  verify-verilog-format:
    name: Check Verilog/SystemVerilog Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run verible-verilog-format in check mode
        uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            extensions/hw
            libs/hw
            unit/src
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          check_only: true
          use_format: true
          verible_config: ci/.rules.verible
