name: ROS 2 Humble Build Check

on:
  push:
    branches: [ main ]
    paths:
      - 'extensions/sw/**'
      - 'libs/sw/**'
      - 'node/**'
      - 'monitor/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'extensions/sw/**'
      - 'libs/sw/**'
      - 'node/**'
      - 'monitor/**'

jobs:
  build:
    name: Build ROS 2 Packages (custom layout)
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: humble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies with rosdep
        run: |
          sudo apt update
          sudo apt install -y ros-humble-pcl-msgs
          rosdep update
          rosdep install \
            --from-paths extensions/sw libs/sw node monitor \
            --ignore-src -r -y

      - name: Build packages with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build \
            --base-paths extensions/sw libs/sw node monitor \
            --event-handlers console_direct+ 
